### ISSUE TITLE
How'd you get woocommerce to use shop folder instead

### ISSUE THREAD

**Issue by imcodingideas** [ouun/stage#308]
Just digging into this theme and wondering how did you tell WooCommerce to use the **resources/views/shop** folder?

**Comment by ouun** [comment]
By using this package: https://github.com/ouun/stage-woocommerce

And exactly with this hook: https://github.com/ouun/stage-woocommerce/blob/d856f0286638afe45657e909d0926b6f6e6d4cb1/src/woocommerce.php#L19
